# fly.toml app configuration file generated for porras on 2023-07-13T12:10:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "porras"
primary_region = "mad"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[deploy.targets]]
  name = "production"
  type = "docker"
  app_id = "porras"

  [deploy.targets.docker]
    image = "tu-imagen-docker"

  [deploy.targets.app]
    env = {
      MYSQL_HOST = "host-de-tu-base-de-datos",
      MYSQL_USER = "usuario-de-tu-base-de-datos",
      MYSQL_PASSWORD = "contraseña-de-tu-base-de-datos",
      MYSQL_DATABASE = "nombre-de-tu-base-de-datos"
    }






